// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DocumentRepository is an autogenerated mock type for the DocumentRepository type
type DocumentRepository struct {
	mock.Mock
}

type DocumentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *DocumentRepository) EXPECT() *DocumentRepository_Expecter {
	return &DocumentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, document
func (_m *DocumentRepository) Create(ctx context.Context, document interface{}) error {
	ret := _m.Called(ctx, document)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, document)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DocumentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type DocumentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - document interface{}
func (_e *DocumentRepository_Expecter) Create(ctx interface{}, document interface{}) *DocumentRepository_Create_Call {
	return &DocumentRepository_Create_Call{Call: _e.mock.On("Create", ctx, document)}
}

func (_c *DocumentRepository_Create_Call) Run(run func(ctx context.Context, document interface{})) *DocumentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *DocumentRepository_Create_Call) Return(_a0 error) *DocumentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DocumentRepository_Create_Call) RunAndReturn(run func(context.Context, interface{}) error) *DocumentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *DocumentRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DocumentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type DocumentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *DocumentRepository_Expecter) Delete(ctx interface{}, id interface{}) *DocumentRepository_Delete_Call {
	return &DocumentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *DocumentRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *DocumentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DocumentRepository_Delete_Call) Return(_a0 error) *DocumentRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DocumentRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *DocumentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *DocumentRepository) List(ctx context.Context, filter interface{}) ([]interface{}, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) ([]interface{}, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) []interface{}); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DocumentRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type DocumentRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
func (_e *DocumentRepository_Expecter) List(ctx interface{}, filter interface{}) *DocumentRepository_List_Call {
	return &DocumentRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *DocumentRepository_List_Call) Run(run func(ctx context.Context, filter interface{})) *DocumentRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *DocumentRepository_List_Call) Return(_a0 []interface{}, _a1 error) *DocumentRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DocumentRepository_List_Call) RunAndReturn(run func(context.Context, interface{}) ([]interface{}, error)) *DocumentRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: ctx, id, document
func (_m *DocumentRepository) Read(ctx context.Context, id string, document interface{}) error {
	ret := _m.Called(ctx, id, document)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, id, document)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DocumentRepository_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type DocumentRepository_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - document interface{}
func (_e *DocumentRepository_Expecter) Read(ctx interface{}, id interface{}, document interface{}) *DocumentRepository_Read_Call {
	return &DocumentRepository_Read_Call{Call: _e.mock.On("Read", ctx, id, document)}
}

func (_c *DocumentRepository_Read_Call) Run(run func(ctx context.Context, id string, document interface{})) *DocumentRepository_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *DocumentRepository_Read_Call) Return(_a0 error) *DocumentRepository_Read_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DocumentRepository_Read_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *DocumentRepository_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, document
func (_m *DocumentRepository) Update(ctx context.Context, id string, document interface{}) error {
	ret := _m.Called(ctx, id, document)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, id, document)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DocumentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type DocumentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - document interface{}
func (_e *DocumentRepository_Expecter) Update(ctx interface{}, id interface{}, document interface{}) *DocumentRepository_Update_Call {
	return &DocumentRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, document)}
}

func (_c *DocumentRepository_Update_Call) Run(run func(ctx context.Context, id string, document interface{})) *DocumentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *DocumentRepository_Update_Call) Return(_a0 error) *DocumentRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DocumentRepository_Update_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *DocumentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewDocumentRepository creates a new instance of DocumentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDocumentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DocumentRepository {
	mock := &DocumentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
