services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      mongo:
        condition: service_started
    networks:
      - app-network
    ports:
      - "8080:8080"
    env_file:
      - .env
  mongo:
    container_name: mongo
    image: mongo:8.0.12
    networks:
      - app-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: grant
      MONGO_INITDB_ROOT_PASSWORD: secret

networks:
  app-network:
